#
# GMT 6.5.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 10p,Helvetica,black
FONT_ANNOT_SECONDARY           = 10p,Helvetica,black
FONT_LABEL                     = 10p,Helvetica,black
FONT_TITLE                     = 12p,Helvetica,black
#
# FORMAT Parameters
#
FORMAT_GEO_MAP                 = ddd:mm:ssF
