#!/usr/bin/env python3
"""
Convert Exodus mesh data (vertices and connectivity) to Gmsh .geo format
Reads the output files from the Exodus reader and creates Gmsh geometry
"""

import sys
import os
from collections import defaultdict, OrderedDict

class ExodusToGmsh:
    def __init__(self):
        self.points = {}
        self.lines = {}
        self.surfaces = {}
        self.volumes = {}
        self.point_counter = 1
        self.line_counter = 1
        self.surface_counter = 1
        self.volume_counter = 1
        
        # Mapping of Exodus element types to Gmsh
        self.element_type_map = {
            'TRI3': 'triangle',
            'TRI6': 'triangle6',
            'QUAD4': 'quad',
            'QUAD8': 'quad8',
            'QUAD9': 'quad9',
            'TET4': 'tetrahedron',
            'TET10': 'tetrahedron10',
            'HEX8': 'hexahedron',
            'HEX20': 'hexahedron20',
            'HEX27': 'hexahedron27',
            'WEDGE6': 'prism',
            'WEDGE15': 'prism15',
            'PYRAMID5': 'pyramid',
            'PYRAMID13': 'pyramid13'
        }
        
        # Element face definitions for surface extraction
        self.element_faces = {
            'TRI3': [[1, 2], [2, 3], [3, 1]],
            'QUAD4': [[1, 2], [2, 3], [3, 4], [4, 1]],
            'TET4': [[1, 2, 3], [1, 2, 4], [2, 3, 4], [1, 3, 4]],
            'HEX8': [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 6, 5], 
                     [3, 4, 8, 7], [2, 3, 7, 6], [1, 4, 8, 5]]
        }

    def read_vertices(self, vertices_file):
        """Read vertex coordinates from the vertices file"""
        print(f"Reading vertices from: {vertices_file}")
        
        with open(vertices_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('#') or not line:
                    continue
                
                parts = line.split()
                if len(parts) >= 3:  # At least node_id, x, y
                    node_id = int(parts[0])
                    x = float(parts[1])
                    y = float(parts[2])
                    z = float(parts[3]) if len(parts) > 3 else 0.0
                    
                    self.points[node_id] = (x, y, z)
        
        print(f"Read {len(self.points)} vertices")

    def read_connectivity(self, connectivity_file):
        """Read element connectivity from the connectivity file"""
        print(f"Reading connectivity from: {connectivity_file}")
        
        elements = []
        
        with open(connectivity_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('#') or not line:
                    continue
                
                parts = line.split()
                if len(parts) >= 3:  # At least elem_id, elem_type, node1
                    elem_id = int(parts[0])
                    elem_type = parts[1]
                    nodes = [int(parts[i]) for i in range(2, len(parts))]
                    
                    elements.append((elem_id, elem_type, nodes))
        
        print(f"Read {len(elements)} elements")
        return elements

    def extract_edges_and_faces(self, elements):
        """Extract unique edges and faces from elements"""
        edges = set()
        faces = defaultdict(list)
        
        for elem_id, elem_type, nodes in elements:
            if elem_type in self.element_faces:
                face_defs = self.element_faces[elem_type]
                
                for face_def in face_defs:
                    if len(face_def) == 2:  # Edge
                        edge = tuple(sorted([nodes[i-1] for i in face_def]))
                        edges.add(edge)
                    elif len(face_def) >= 3:  # Face
                        face_nodes = tuple(sorted([nodes[i-1] for i in face_def]))
                        faces[face_nodes].append(elem_id)
        
        # Keep only boundary faces (faces that belong to only one element)
        boundary_faces = {face: elems for face, elems in faces.items() if len(elems) == 1}
        
        print(f"Extracted {len(edges)} edges and {len(boundary_faces)} boundary faces")
        return edges, boundary_faces

    def write_geo_file(self, output_file, elements, edges=None, boundary_faces=None):
        """Write the Gmsh .geo file"""
        print(f"Writing Gmsh .geo file: {output_file}")
        
        with open(output_file, 'w') as f:
            # Write header
            f.write("// Gmsh geometry file generated from Exodus mesh data\n")
            f.write("// Generated by exodus_to_gmsh.py\n\n")
            
            # Set mesh size factor
            f.write("// Mesh size factor\n")
            f.write("lc = 1.0;\n\n")
            
            # Write points
            f.write("// Points\n")
            for node_id, (x, y, z) in sorted(self.points.items()):
                f.write(f"Point({node_id}) = {{{x:.6f}, {y:.6f}, {z:.6f}, lc}};\n")
            f.write("\n")
            
            # Write lines (edges) if available
            if edges:
                f.write("// Lines\n")
                line_id = 1
                line_map = {}
                for edge in sorted(edges):
                    f.write(f"Line({line_id}) = {{{edge[0]}, {edge[1]}}};\n")
                    line_map[edge] = line_id
                    line_id += 1
                f.write("\n")
            
            # Write surfaces for 2D elements or boundary faces
            surface_elements = []
            
            # Check if we have 2D elements
            for elem_id, elem_type, nodes in elements:
                if elem_type in ['TRI3', 'TRI6', 'QUAD4', 'QUAD8', 'QUAD9']:
                    surface_elements.append((elem_id, elem_type, nodes))
            
            if surface_elements:
                f.write("// Surfaces (2D elements)\n")
                for elem_id, elem_type, nodes in surface_elements:
                    if elem_type.startswith('TRI'):
                        f.write(f"// Triangle {elem_id}\n")
                        # Create lines for triangle edges
                        edges_for_tri = [
                            (nodes[0], nodes[1]),
                            (nodes[1], nodes[2]),
                            (nodes[2], nodes[0])
                        ]
                        line_ids = []
                        for i, edge in enumerate(edges_for_tri):
                            line_num = elem_id * 10 + i + 1
                            f.write(f"Line({line_num}) = {{{edge[0]}, {edge[1]}}};\n")
                            line_ids.append(line_num)
                        
                        loop_num = elem_id * 10
                        f.write(f"Line Loop({loop_num}) = {{{', '.join(map(str, line_ids))}}};\n")
                        f.write(f"Plane Surface({elem_id}) = {{{loop_num}}};\n\n")
                    
                    elif elem_type.startswith('QUAD'):
                        f.write(f"// Quadrilateral {elem_id}\n")
                        # Create lines for quad edges
                        edges_for_quad = [
                            (nodes[0], nodes[1]),
                            (nodes[1], nodes[2]),
                            (nodes[2], nodes[3]),
                            (nodes[3], nodes[0])
                        ]
                        line_ids = []
                        for i, edge in enumerate(edges_for_quad):
                            line_num = elem_id * 10 + i + 1
                            f.write(f"Line({line_num}) = {{{edge[0]}, {edge[1]}}};\n")
                            line_ids.append(line_num)
                        
                        loop_num = elem_id * 10
                        f.write(f"Line Loop({loop_num}) = {{{', '.join(map(str, line_ids))}}};\n")
                        f.write(f"Plane Surface({elem_id}) = {{{loop_num}}};\n\n")
            
            # Write physical groups for organization
            f.write("// Physical groups\n")
            
            # Group 2D elements
            if surface_elements:
                surface_ids = [elem_id for elem_id, _, _ in surface_elements]
                f.write(f"Physical Surface(\"Surface_Elements\") = {{{', '.join(map(str, surface_ids))}}};\n")
            
            # Group 3D elements if any
            volume_elements = []
            for elem_id, elem_type, nodes in elements:
                if elem_type in ['TET4', 'TET10', 'HEX8', 'HEX20', 'HEX27', 'WEDGE6', 'WEDGE15', 'PYRAMID5', 'PYRAMID13']:
                    volume_elements.append((elem_id, elem_type, nodes))
            
            if volume_elements:
                f.write("// Note: 3D elements found but not fully implemented in this version\n")
                f.write(f"// 3D elements: {len(volume_elements)} volumes\n")
            
            f.write("\n// End of geometry file\n")

    def convert(self, vertices_file, connectivity_file, output_file='mesh.geo'):
        """Main conversion function"""
        print("Starting Exodus to Gmsh conversion...")
        
        # Read input files
        self.read_vertices(vertices_file)
        elements = self.read_connectivity(connectivity_file)
        
        if not self.points:
            print("Error: No vertices found!")
            return False
        
        if not elements:
            print("Error: No elements found!")
            return False
        
        # Extract geometric features
        edges, boundary_faces = self.extract_edges_and_faces(elements)
        
        # Write Gmsh .geo file
        self.write_geo_file(output_file, elements, edges, boundary_faces)
        
        print(f"Conversion completed successfully!")
        print(f"Generated: {output_file}")
        print(f"To create mesh in Gmsh: gmsh {output_file} -2 (for 2D) or gmsh {output_file} -3 (for 3D)")
        
        return True

def main():
    """Main function to handle command line arguments"""
    
    if len(sys.argv) < 3:
        print("Usage: python exodus_to_gmsh.py <vertices_file> <connectivity_file> [output.geo]")
        print("Example: python exodus_to_gmsh.py vertices.txt connectivity.txt mesh.geo")
        sys.exit(1)
    
    vertices_file = sys.argv[1]
    connectivity_file = sys.argv[2]
    output_file = sys.argv[3] if len(sys.argv) > 3 else 'mesh.geo'
    
    # Check if input files exist
    for filename in [vertices_file, connectivity_file]:
        if not os.path.exists(filename):
            print(f"Error: Input file '{filename}' does not exist")
            sys.exit(1)
    
    # Create converter and run conversion
    converter = ExodusToGmsh()
    success = converter.convert(vertices_file, connectivity_file, output_file)
    
    if not success:
        print("Conversion failed!")
        sys.exit(1)

if __name__ == "__main__":
    main()